name: 'ecom_dbt'
version: '1.0.0'
profile: 'ecom_profile'

model-paths: ['models']
snapshot-paths: ['snapshots']

models:
  ecom_dbt:
    staging:
      +schema: staging
    marts:
      +schema: marts
